include: package:flutter_lints/flutter.yaml
analyzer:
    exclude: 
      - '**/*.gen.dart'
linter:
  rules:
     avoid_print: true
     prefer_single_quotes: true
     always_declare_return_types: true
     require_trailing_commas: true